FROM ruby:3.4.2
RUN apt-get update -qq && apt-get install -y nodejs default-mysql-client
WORKDIR /rails_app
COPY Gemfile Gemfile.lock ./
RUN gem install bundler && bundle install --without development test
COPY . .
RUN RAILS_ENV=production bundle exec rails assets:precompile